import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medical-device-chargeback-rebate-reconciliation",
  "engine": "recovery",
  "title": "Medical Device Chargeback & Rebate Reconciliation",
  "shortTitle": "Medical Device Chargeback and Rebate Reconciliation",
  "tagline": "Validate distributor chargebacks and calculate earned rebates, price protection, and contract credits at device and customer level.",
  "industry": "Medical Device Commercial Finance",
  "buyer": "Medical-device manufacturers",
  "uiPort": 4656,
  "apiPort": 5656,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Medical Device Chargeback & Rebate Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions in one accountable workflow. Validate distributor chargebacks and calculate earned rebates, price protection, and contract credits at device and customer level.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Medical Device Chargeback & Rebate Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("contract-price-library","MDC01","Contract price library","Execute contract price library using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed contract price library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Contract price library Reference","text","MDC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("distributor-customer-mapping","MDC02","Distributor customer mapping","Execute distributor customer mapping using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed distributor customer mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Distributor customer mapping Reference","text","MDC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("device-sku-registry","MDC03","Device SKU registry","Execute device sku registry using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed device sku registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Device SKU registry Reference","text","MDC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("sales-trace-ingestion","MDC04","Sales trace ingestion","Execute sales trace ingestion using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed sales trace ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Sales trace ingestion Reference","text","MDC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("eligibility-validation","MDC05","Eligibility validation","Execute eligibility validation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed eligibility validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Eligibility validation Reference","text","MDC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("contract-price-calculation","MDC06","Contract price calculation","Execute contract price calculation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed contract price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Contract price calculation Reference","text","MDC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("chargeback-validation","MDC07","Chargeback validation","Execute chargeback validation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed chargeback validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Chargeback validation Reference","text","MDC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("duplicate-claim-detection","MDC08","Duplicate claim detection","Execute duplicate claim detection using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed duplicate claim detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Duplicate claim detection Reference","text","MDC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("volume-rebate-calculation","MDC09","Volume rebate calculation","Execute volume rebate calculation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed volume rebate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Volume rebate calculation Reference","text","MDC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("price-protection-calculation","MDC10","Price-protection calculation","Execute price-protection calculation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed price-protection calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Price-protection calculation Reference","text","MDC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("return-credit-coordination","MDC11","Return credit coordination","Execute return credit coordination using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed return credit coordination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Return credit coordination Reference","text","MDC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("distributor-deduction-matching","MDC12","Distributor deduction matching","Execute distributor deduction matching using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed distributor deduction matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Distributor deduction matching Reference","text","MDC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("dispute-workflow","MDC13","Dispute workflow","Execute dispute workflow using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Dispute workflow Reference","text","MDC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("settlement-reconciliation","MDC14","Settlement reconciliation","Execute settlement reconciliation using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Settlement reconciliation Reference","text","MDC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]}),
feature("device-channel-analytics","MDC15","Device channel analytics","Execute device channel analytics using customer contracts, distributor sales, device SKUs, lot and serial data, chargebacks, rebates, returns, eligibility, credits, and deductions.","Produce a governed device channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Distributor / Device Contract","text","Distributor / Device Contract · Standard Case"],["caseReference","Device channel analytics Reference","text","MDC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",686250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",830363],["domainDriver","Program Type","select","Distributor chargeback",["Distributor chargeback","Volume rebate","Price protection"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract price library case","Distributor customer mapping case","Device SKU registry case","Sales trace ingestion case","Eligibility validation case"]})
]);
